### PR TITLE
Replace the theme with simple styles and templates

### PR DESCRIPTION
**Pull request by mwcampbell**
It was brought to my attention that the AccessKit home page looked ugly on a phone. Then I decided to test the site with [WebPageTest](https://www.webpagetest.org/easy) and found that the load performance, while not bad, was not optimal, due to a render-blocking request on some JavaScript (brought in by the theme) among other things.

So I decided to drop the theme and go with styles and templates derived from the [Linebender site](https://linebender.org/), but stripped down further and adapted to prioritize accessibility above all, by not specifying specific colors or fonts. I decided that we need way less than the theme gave us, and even less than the Linebender template has. I also decided that we don't need Sass, just static CSS.

I'd like to get this PR reviewed by at least one fully sighted person who knows CSS. Then when that's done, we should have something truly minimal that we can fully understand and maintain.

### CODE REVIEW

**Comment by DataTriny** [comment]
Code looks good to me.

The appearance is from a past era, but if that's what people want.

**Comment by mwcampbell** [comment]
About the appearance being from a past era, I understand, at least abstractly, the need to make the site attractive to sighted people, or at least not noticeably ugly. But that shouldn't come at the expense of putting disabled people first (especially since this is an accessibility project), particularly in making it as easy as possible to customize the font and colors. I also want to keep the site lean. I wonder what aspects of the appearance most strongly evoke the feeling of being from a past era, and if these can be fixed without compromising the other goals.

**Comment by mwcampbell** [comment]
I guess the appearance is from a past era because, as rendered by typical browsers, the site has a serif font and is all black and white. But it seems to me that we can't change these things without compromising on putting the user's preferences first.

**Comment by welpo** [comment]
Hello!

I'm the author of the tabi theme. I understand the requirements to make the AccessKit's page as accessible as possible.

I have fixed the overlapping text issue for small screens (https://github.com/welpo/tabi/issues/374), but I understand there are other concerns.

In case you decide to stick with tabi, I'd like to point out:
- Any accessibility issues found I strive to fix as quickly as possible; accessibility is a priority
- You can completely disable JavaScript without missing on any vital functionality for the theme. The load-blocking script is the dark/light theme initialiser. It can be disabled whilst still respecting the users OS dark/light theme preference. To achieve this, set `theme_switcher = false` in the `[extra]` section of `config.toml`. [Docs on JavaScript being optional](https://welpo.github.io/tabi/blog/javascript/)
- Regarding respecting the user font (any any other settings you may want to change), this can be forced with the use of a `skin`, which gets loaded on all pages and overrides the tabi CSS. Here are [the docs](https://welpo.github.io/tabi/blog/customise-tabi/#skins)

In the end, I understand you'll choose what's best for users, and that may well be a stripped down HTML+CSS site. I just wanted to hop in to say I'd be honoured to see tabi being used to support the AccessKit project.

I'd be happy to answer any questions or address any concerns you may have.

Best,

—Óscar

**Comment by mwcampbell** [comment]
@welpo Thanks for taking time to fix that multi-line heading bug and comment here. I appreciate the work you do on Tabi, including your efforts to make it accessible.

However, I think that for the target audience, as well as this project's emphasis on accessibility above all else, it's better to use minimal HTML and CSS tailored for the site.

I'll keep Tabi in mind for future projects, though. Thanks again.

**Pull request merged**
